### ISSUE TITLE
Examples are always built

### ISSUE THREAD

**Issue by MPcoreDev** [batterycenter/embed#2]
Hello.
Thank you for sharing this code. That's very usefull.
I embed the project as a submodule like I do with other externals.
My issue is that the examples are built, even if I have a `project()` statement at the begining of my project.
I think that the issue is that I define BUILD_EXAMPLES because I want the examples to be build for my project.
In modern cmake examples, they propose the following to avoid this issue:
```
# Testing only available if this is the main app
# Emergency override MODERN_CMAKE_BUILD_TESTING provided as well
if((CMAKE_PROJECT_NAME STREQUAL PROJECT_NAME OR MODERN_CMAKE_BUILD_TESTING)
   AND BUILD_TESTING)
  add_subdirectory(tests)
endif()
```
https://gitlab.com/CLIUtils/modern-cmake/-/blob/master/examples/extended-project/CMakeLists.txt#L62

**Comment by HerrNamenlos123** [comment]
I released a new version where this is fixed.
I simply used `if (PROJECT_IS_TOP_LEVEL AND BUILD_EXAMPLES)`, since that is what I already use anyways.

**Comment by HerrNamenlos123** [comment]
@MPcoreDev for your information, according to https://github.com/conan-io/conan-center-index/pull/22698, there was also an issue regarding the examples being built when they shouldn't, in relation to Conan support. In the end I ended up, just renaming the flag to `BATTERY_EMBED_BUILD_EXAMPLES` and in the process I removed the TOP_LEVEL flag. So now, `BATTERY_EMBED_BUILD_EXAMPLES` defaults to true when it is the top level project, otherwise it defaults to false, and it can always be explicitly overridden. I think this is the most universal solution.

Let me know if there is an issue with that implementation in Version 1.2.13.
