### ISSUE TITLE
Any way to use it without hard coded string literals ?

### ISSUE THREAD

**Issue by JD31** [batterycenter/embed#8]
I am able to use embed like in the examples:   
`b::embed<"folder/my_res.glsl">`

But I would need to use a variable instead of the string literal. Something like:  
```
constexpr std::string_view sv = "folder/my_res.glsl";
b::embed<sv> // does not work
```

Is there any way to achieve this ?
Thank you

**Comment by HerrNamenlos123** [comment]
To clarify, what exactly do you want to achieve? You want to use a string from a variable, but the variable is still constexpr and known at compile time?

If the variable is not known at compile time (loading dynamically at runtime), this is not yet supported and I would highly advise against such a design.

If it is, and the variable is a constexpr string_view, it should actually work. Can you give me an error message? I think the example you gave should work in theory

**Comment by HerrNamenlos123** [comment]
One thing you could try, if I remember correctly, string_view could not be used as a template parameter. This is why I created a custom constexpr string class that takes a literal.

Please take a look at the implementation of b::embed in the generated header embed.hpp. There should be a constexpr string class used in the template of b::embed. Please try if you can use this class instead of string_view.

**Comment by HerrNamenlos123** [comment]
https://github.com/batterycenter/embed/blob/main/CMakeLists.txt#L252

It should be here. I have not tried it but please try if you can use b::embed_string_literal

**Comment by JD31** [comment]
Nice, it works with the `embed_string_literal`  
The end solution for the question is then :   
```
constexpr b::embed_string_literal sv = "folder/my_res.glsl";
b::embed<sv> // does work
```
Thank you

**Comment by HerrNamenlos123** [comment]
Very nice, good to know that this works in case someone needs it. Thanks!
